### ISSUE TITLE
[server side] How do I implement and expose subscriptions?

### ISSUE THREAD

**Issue by jyjyj** [kobylynskyi/graphql-java-codegen#265]
As mentioned in the question above. As far as I can tell, the resolvers for subscriptions should be implemented with the `reactivestreams` `Publisher`, but that does not seem to be the type shown in the generated interface. For example, I have

```
type Subscription {
    testSub: Boolean!
}
```

If my understanding is correct, I'm expecting to implement a `Publisher<Boolean>`, but right now I'm simply getting a normal `Boolean` return type on the interface method.

Another related question: how do I expose the necessary websockets on the server side for these subscriptions? I have tried `.subscriptionExecutionStrategy(new SubscriptionExecutionStrategy())` from [here](https://www.graphql-java.com/documentation/v9/subscriptions/) but it doesn't seem to do anything different.

Thanks!

**Comment by jxnu-liguobin** [comment]
I just saw that. you maybe need async returnType like `Publisher` ?  I think I can give some simple answers.

You can use option `apiAsyncReturnType`  such as `apiAsyncReturnType := "scala.concurrent.Future"` in  sbt

`apiAsyncReturnType` also can use in gradle or maven

if resultType is `Collection` ,  use `apiAsyncReturnListType`

**Comment by jxnu-liguobin** [comment]
Sorry, at first I thought you just needed to return async type.

in  sbt plugin you can use option `apiAsyncReturnType`  such as 
```scala
generateAsyncApi := true
apiAsyncReturnType := "scala.concurrent.Future" //your type: Publisher
``` 
also can use in gradle plugin
```
generateAsyncApi = true
apiAsyncReturnType = "scala.concurrent.Future"
```

if resultType is `Collection` ,  use `apiAsyncReturnListType`

**but if you want use in subscription**

you can use `subscriptionReturnType `

like

```
subscriptionReturnType := Some("org.reactivestreams.Publisher")
```

also can use in gradle plugin
```
subscriptionReturnType = "org.reactivestreams.Publisher"
```

when you exec task, will generate java code
```java
public interface SubscriptionResolver {

    @javax.validation.constraints.NotNull
    org.reactivestreams.Publisher<Boolean> testSub() throws Exception;

}
```

**Comment by jyjyj** [comment]
@jxnu-liguobin thank you! I tried your 2nd solution and that is indeed what I need for subscriptions. 

May I ask a follow-up if not too much trouble - how should the implementation of the function be done to return a Publish<> type, and how do you expose a WebSocket link for the subscriptions? 

Thank you!

**Comment by jxnu-liguobin** [comment]
Haha, i am sorry, I just wrote a sbt plugin and never used the subscription of graphql.
But I think the subscription' server is also a `mutation fetcher`, client also like query/mutation.

**Comment by kobylynskyi** [comment]
@jyjyj here's an example of SubscriptionResolver:

```java
@Component
public class EventsSubscriptionResolver implements GraphQLSubscriptionResolver {

    private static final int BATCH_SIZE = 50;

    private Flowable<LogUpdatedEvent> logUpdatesFlowable
    // init publisher

    public Publisher<Collection<LogUpdateEventTO>> logs(String eventId) {
        return logUpdatesFlowable
                .filter(event -> event.getEventId().equalsIgnoreCase(eventId))
                .buffer(1, TimeUnit.SECONDS, BATCH_SIZE)
                .filter(l -> !l.isEmpty())
                .map(logUpdateEventMapper::mapCollection);
    }
}
```
If you are using the latest graphql-java version, then you can define subscrition url in application.yml:
```yml
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    cors:
      allowed-origins: '*'
      allowed-methods: 'GET, POST, OPTIONS'
      allowed-headers: 'origin, content-type, authorization, accept, x-requested-with, sec-websocket-protocol, sec-websocket-extensions, sec-websocket-key, sec-websocket-version'
      max-age: 3600
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
    subscriptions:
      websocket:
        path: /graphql/subscriptions
```
